kind: pipeline
type: docker
name: default

steps:
- name: Preload
  image: drone/git
  commands:
  - apt-get install -y gcc
  - echo installed

- name: Build
  image: drone/git
  commands:
  - gcc -no-pie -fno-stack-protector target5.c
  - echo compiled
  - checksec a.out
  - file a.out

- name: Exploit_load
  image: drone/git
  commands:
  - apt-get install python3 python3-pip python3-dev git libssl-dev libffi-dev build-essential
  - python3 -m pip install --upgrade pip
  - python3 -m pip install --upgrade pwntools
  - exploit loaded

- name: Exploit_run
  image: pwntools/pwntools:latest
  commands:
  - python3 _pwn5.py
  - echo exploited
